# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael I Mandel
email: mim@mr-pc.org
description: > # this means to ignore newlines until "baseurl:"
  I analyze sound with machine learning and signal
  processing.  I am currently building machines that emulate the
  remarkable ability of humans to recognize speech in noise.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mr-pc.org" # the base hostname & protocol for your site
twitter_username: mimasterix
github_username:  mim

# Build settings
markdown: kramdown
