#!/bin/bash -x
set -e

# Convert all of the .aux files generated by my cv to a single
# sectioned html page.

AUXS=(1 2 3 4)
FILES=(chapter journal conference workshop)
NAMES=("Book chapter" "Journal" "Conference" "Other")

ALLHTML=pubs.html
ALLBIBHTML=pubs_bib.html
ALLABSHTML=pubs_abs.html
HTMLDIR=~/html/work

for file in $ALLHTML $ALLABSHTML ; do
    cat > $file <<EOF
<html>
<head>
  <title>Michael I Mandel's publications</title>
  <style type="text/css" media="all">@import "/inc/bluerobot.css";</style>
  <link rel="shortcut icon" href="/favicon.ico" />
</head>
<body>

<h1 id="Header">Publications</h1>

<div class="Content">
EOF
done

cat > $ALLBIBHTML <<EOF
<html>
<head>
  <title>Bibtex for Michael I Mandel's publications</title>
  <style type="text/css" media="all">@import "/inc/bluerobot.css";</style>
  <link rel="shortcut icon" href="/favicon.ico" />
</head>
<body>

<div class="Content">
EOF

for n in `seq ${#AUXS[@]}` ; do 
    AUX=${AUXS[$n-1]}
    NAME=${NAMES[$n-1]}
    FILE=${FILES[$n-1]}

    BIB="mandel_${FILE}.bib"
    HTML="mandel_${FILE}.html"
    BIBHTML="mandel_${FILE}_bib.html"
    ABSHTML="mandel_${FILE}_abstracts.html"

    aux2bib bu$AUX.aux | grep -v \@comment > $BIB
    bibtex2html --both -nf poster Poster -nf slides Slides -nf http http $BIB

    # Strip off headers and footers
    for file in $HTML $ABSHTML ; do
        sed -i "0,/<table>/d" $file
        sed -i "\|</table>|,+22d" $file
        sed -i "s/$BIBHTML/$ALLBIBHTML/" $file
        sed -i "s/$ABSHTML/$ALLABSHTML/" $file
    done
    
    echo -e "<h2>$NAME</h2>\n<table>\n" >> $ALLHTML
    cat $HTML >> $ALLHTML
    echo -e "</table>\n" >> $ALLHTML

    echo -e "<h2>$NAME</h2>\n<table>\n" >> $ALLABSHTML
    cat $ABSHTML >> $ALLABSHTML
    echo -e "</table>\n" >> $ALLABSHTML

    # Strip off headers and footers of bib html files
    sed -i "0,/<body>/d" $BIBHTML
    sed -i "\|<hr><p><em>|,+22d" $BIBHTML
    sed -i "s/$BIB/$NAME/" $BIBHTML
    cat $BIBHTML >> $ALLBIBHTML

    rm $BIB
    rm $HTML
    rm $BIBHTML
    rm $ABSHTML
done

for file in $ALLHTML $ALLABSHTML $ALLBIBHTML ; do
    cat >> $file <<EOF
</div>
<div class="Content">
  <center>
  <img src="/inc/addr3.png">
  <img src="/inc/bullet.gif">
  <a href="http://mr-pc.org">mr-pc.org</a>
  <img src="/inc/bullet.gif">
  <!--#config timefmt="%A %B %d, %Y" -->
  <!--#config timefmt="%m.%d.%Y" -->
  updated <!--#echo var="LAST_MODIFIED" --> <br />
  Copyright &copy; 2004-9 Michael I Mandel
  </center>
</div>

<script src="http://www.google-analytics.com/urchin.js"
  type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-2220648-1";
urchinTracker();
</script>
</body>
</html>
EOF
done

mv $ALLHTML $ALLBIBHTML $ALLABSHTML $HTMLDIR
