#!/bin/bash -xue

# Convert all of the .aux files generated by my cv to a single
# sectioned html page.

AUXS=(1 2 3 4)
FILES=(journal chapter conference workshop)
NAMES=("Journal" "Theses, Chapters" "Conference" "Other")

AUXDIR=~/doc/cv
ALLHTML=pubs.html
ALLBIBHTML=pubs_bib.html
ALLABSHTML=pubs_abs.html
HTMLDIR=~/code/www/

for file in $ALLHTML $ALLABSHTML ; do
    cat > $file <<EOF
---
layout: default
title: Publications -- Michael I Mandel
---
<div class="page-header">
<h1>Publications</h1>
</div>
EOF
done

cat > $ALLBIBHTML <<EOF
---
layout: default
title: BibTeX for Publications -- Michael I Mandel
---
<div class="page-header">
<h1>Publications</h1>
</div>
EOF

for n in `seq ${#AUXS[@]}` ; do 
    AUX=${AUXS[$n-1]}
    NAME=${NAMES[$n-1]}
    FILE=${FILES[$n-1]}

    BIB="mandel_${FILE}.bib"
    HTML="mandel_${FILE}.html"
    BIBHTML="mandel_${FILE}_bib.html"
    ABSHTML="mandel_${FILE}_abstracts.html"

    ( cd $AUXDIR ; aux2bib bu$AUX.aux | grep -v \@comment ) > $BIB
    bibtex2html --both -nf poster Poster -nf slides Slides -nf http Demo -nf code Code $BIB

    # Strip off headers and footers
    for file in $HTML $ABSHTML ; do
        sed -i "0,/<table>/d" $file
        sed -i "\|</table>|,+22d" $file
        sed -i "s/$BIBHTML/$ALLBIBHTML/" $file
        sed -i "s/$ABSHTML/$ALLABSHTML/" $file
    done
    
    echo -e "<h2>$NAME</h2>\n<table>\n" >> $ALLHTML
    cat $HTML >> $ALLHTML
    echo -e "</table>\n" >> $ALLHTML

    echo -e "<h2>$NAME</h2>\n<table>\n" >> $ALLABSHTML
    cat $ABSHTML >> $ALLABSHTML
    echo -e "</table>\n" >> $ALLABSHTML

    # Strip off headers and footers of bib html files
    sed -i "0,/<body>/d" $BIBHTML
    sed -i "\|<hr><p><em>|,+22d" $BIBHTML
    sed -i "s/$BIB/$NAME/" $BIBHTML
    cat $BIBHTML >> $ALLBIBHTML

    rm $BIB
    rm $HTML
    rm $BIBHTML
    rm $ABSHTML
done

mv $ALLHTML $ALLBIBHTML $ALLABSHTML $HTMLDIR
